// country_data.dart
final List<Map<String, String>> worldLocations = [
  {'name': 'New York', 'timezone': 'America/New_York', 'countryCode': 'us'},
  {'name': 'Beijing', 'timezone': 'Asia/Shanghai', 'countryCode': 'cn'},
  {'name': 'Dubai', 'timezone': 'Asia/Dubai', 'countryCode': 'ae'},
  {'name': 'London', 'timezone': 'Europe/London', 'countryCode': 'gb'},
  {'name': 'Tokyo', 'timezone': 'Asia/Tokyo', 'countryCode': 'jp'},
  {'name': 'Sydney', 'timezone': 'Australia/Sydney', 'countryCode': 'au'},
  {'name': 'Paris', 'timezone': 'Europe/Paris', 'countryCode': 'fr'},
  {'name': 'Moscow', 'timezone': 'Europe/Moscow', 'countryCode': 'ru'},
  {'name': 'Cape Town', 'timezone': 'Africa/Johannesburg', 'countryCode': 'za'},
  {'name': 'Toronto', 'timezone': 'America/Toronto', 'countryCode': 'ca'},
  {'name': 'Berlin', 'timezone': 'Europe/Berlin', 'countryCode': 'de'},
  {'name': 'Delhi', 'timezone': 'Asia/Kolkata', 'countryCode': 'in'},
  {
    'name': 'Mexico City',
    'timezone': 'America/Mexico_City',
    'countryCode': 'mx'
  },
  {'name': 'Bangkok', 'timezone': 'Asia/Bangkok', 'countryCode': 'th'},
  {'name': 'Istanbul', 'timezone': 'Europe/Istanbul', 'countryCode': 'tr'},
  {'name': 'Singapore', 'timezone': 'Asia/Singapore', 'countryCode': 'sg'},
  {
    'name': 'Buenos Aires',
    'timezone': 'America/Argentina/Buenos_Aires',
    'countryCode': 'ar'
  },
  {'name': 'Cairo', 'timezone': 'Africa/Cairo', 'countryCode': 'eg'},
  {'name': 'Seoul', 'timezone': 'Asia/Seoul', 'countryCode': 'kr'},
  {'name': 'Madrid', 'timezone': 'Europe/Madrid', 'countryCode': 'es'},
  {'name': 'Rome', 'timezone': 'Europe/Rome', 'countryCode': 'it'},
  {'name': 'Nairobi', 'timezone': 'Africa/Nairobi', 'countryCode': 'ke'},
  {'name': 'Hong Kong', 'timezone': 'Asia/Hong_Kong', 'countryCode': 'hk'},
  {
    'name': 'Buenos Aires',
    'timezone': 'America/Argentina/Buenos_Aires',
    'countryCode': 'ar'
  },
  {'name': 'Brisbane', 'timezone': 'Australia/Brisbane', 'countryCode': 'au'},
  {'name': 'Vienna', 'timezone': 'Europe/Vienna', 'countryCode': 'at'},
  {'name': 'Brussels', 'timezone': 'Europe/Brussels', 'countryCode': 'be'},
  {'name': 'Brasilia', 'timezone': 'America/Sao_Paulo', 'countryCode': 'br'},
  {'name': 'Sofia', 'timezone': 'Europe/Sofia', 'countryCode': 'bg'},
  {'name': 'Santiago', 'timezone': 'America/Santiago', 'countryCode': 'cl'},
  {'name': 'Bogotá', 'timezone': 'America/Bogota', 'countryCode': 'co'},
  {'name': 'Zagreb', 'timezone': 'Europe/Zagreb', 'countryCode': 'hr'},
  {'name': 'Havana', 'timezone': 'America/Havana', 'countryCode': 'cu'},
  {'name': 'Copenhagen', 'timezone': 'Europe/Copenhagen', 'countryCode': 'dk'},
  {'name': 'Cairo', 'timezone': 'Africa/Cairo', 'countryCode': 'eg'},
  {'name': 'Helsinki', 'timezone': 'Europe/Helsinki', 'countryCode': 'fi'},
  {'name': 'Athens', 'timezone': 'Europe/Athens', 'countryCode': 'gr'},
  {'name': 'Budapest', 'timezone': 'Europe/Budapest', 'countryCode': 'hu'},
  {'name': 'Jakarta', 'timezone': 'Asia/Jakarta', 'countryCode': 'id'},
  {'name': 'Tehran', 'timezone': 'Asia/Tehran', 'countryCode': 'ir'},
  {'name': 'Baghdad', 'timezone': 'Asia/Baghdad', 'countryCode': 'iq'},
  {'name': 'Jerusalem', 'timezone': 'Asia/Jerusalem', 'countryCode': 'il'},
  {'name': 'Rome', 'timezone': 'Europe/Rome', 'countryCode': 'it'},
  {'name': 'Kingston', 'timezone': 'America/Jamaica', 'countryCode': 'jm'},
  {'name': 'Amman', 'timezone': 'Asia/Amman', 'countryCode': 'jo'},
  {'name': 'Nairobi', 'timezone': 'Africa/Nairobi', 'countryCode': 'ke'},
  {'name': 'Kuwait City', 'timezone': 'Asia/Kuwait', 'countryCode': 'kw'},
  {'name': 'Riga', 'timezone': 'Europe/Riga', 'countryCode': 'lv'},
  {'name': 'Beirut', 'timezone': 'Asia/Beirut', 'countryCode': 'lb'},
  {'name': 'Vilnius', 'timezone': 'Europe/Vilnius', 'countryCode': 'lt'},
  {
    'name': 'Luxembourg City',
    'timezone': 'Europe/Luxembourg',
    'countryCode': 'lu'
  },
  {
    'name': 'Kuala Lumpur',
    'timezone': 'Asia/Kuala_Lumpur',
    'countryCode': 'my'
  },
  {'name': 'Valletta', 'timezone': 'Europe/Malta', 'countryCode': 'mt'},
  {
    'name': 'Mexico City',
    'timezone': 'America/Mexico_City',
    'countryCode': 'mx'
  },
  {'name': 'Monaco', 'timezone': 'Europe/Monaco', 'countryCode': 'mc'},
  {'name': 'Ulaanbaatar', 'timezone': 'Asia/Ulaanbaatar', 'countryCode': 'mn'},
  {'name': 'Podgorica', 'timezone': 'Europe/Podgorica', 'countryCode': 'me'},
  {'name': 'Casablanca', 'timezone': 'Africa/Casablanca', 'countryCode': 'ma'},
  {'name': 'Kathmandu', 'timezone': 'Asia/Kathmandu', 'countryCode': 'np'},
  {'name': 'Wellington', 'timezone': 'Pacific/Auckland', 'countryCode': 'nz'},
  {'name': 'Oslo', 'timezone': 'Europe/Oslo', 'countryCode': 'no'},
  {'name': 'Muscat', 'timezone': 'Asia/Muscat', 'countryCode': 'om'},
  {'name': 'Islamabad', 'timezone': 'Asia/Karachi', 'countryCode': 'pk'},
  {'name': 'Panama City', 'timezone': 'America/Panama', 'countryCode': 'pa'},
  {'name': 'Asunción', 'timezone': 'America/Asuncion', 'countryCode': 'py'},
  {'name': 'Lima', 'timezone': 'America/Lima', 'countryCode': 'pe'},
  {'name': 'Warsaw', 'timezone': 'Europe/Warsaw', 'countryCode': 'pl'},
  {'name': 'Lisbon', 'timezone': 'Europe/Lisbon', 'countryCode': 'pt'},
  {'name': 'Doha', 'timezone': 'Asia/Qatar', 'countryCode': 'qa'},
  {'name': 'Bucharest', 'timezone': 'Europe/Bucharest', 'countryCode': 'ro'},
  {'name': 'Moscow', 'timezone': 'Europe/Moscow', 'countryCode': 'ru'},
  {'name': 'Riyadh', 'timezone': 'Asia/Riyadh', 'countryCode': 'sa'},
  {'name': 'Belgrade', 'timezone': 'Europe/Belgrade', 'countryCode': 'rs'},
  {'name': 'Singapore', 'timezone': 'Asia/Singapore', 'countryCode': 'sg'},
  {'name': 'Bratislava', 'timezone': 'Europe/Bratislava', 'countryCode': 'sk'},
  {'name': 'Ljubljana', 'timezone': 'Europe/Ljubljana', 'countryCode': 'si'},
  {'name': 'Pretoria', 'timezone': 'Africa/Johannesburg', 'countryCode': 'za'},
  {'name': 'Madrid', 'timezone': 'Europe/Madrid', 'countryCode': 'es'},
  {'name': 'Colombo', 'timezone': 'Asia/Colombo', 'countryCode': 'lk'},
  {'name': 'Stockholm', 'timezone': 'Europe/Stockholm', 'countryCode': 'se'},
  {'name': 'Bern', 'timezone': 'Europe/Zurich', 'countryCode': 'ch'},
  {'name': 'Damascus', 'timezone': 'Asia/Damascus', 'countryCode': 'sy'},
  {'name': 'Taipei', 'timezone': 'Asia/Taipei', 'countryCode': 'tw'},
  {'name': 'Dushanbe', 'timezone': 'Asia/Dushanbe', 'countryCode': 'tj'},
  {'name': 'Bangkok', 'timezone': 'Asia/Bangkok', 'countryCode': 'th'},
  {'name': 'Tunis', 'timezone': 'Africa/Tunis', 'countryCode': 'tn'},
  {'name': 'Ankara', 'timezone': 'Europe/Istanbul', 'countryCode': 'tr'},
  {'name': 'Ashgabat', 'timezone': 'Asia/Ashgabat', 'countryCode': 'tm'},
  {'name': 'Kyiv', 'timezone': 'Europe/Kiev', 'countryCode': 'ua'},
  {'name': 'Abu Dhabi', 'timezone': 'Asia/Dubai', 'countryCode': 'ae'},
  {'name': 'London', 'timezone': 'Europe/London', 'countryCode': 'gb'},
  {'name': 'Montevideo', 'timezone': 'America/Montevideo', 'countryCode': 'uy'},
  {'name': 'Caracas', 'timezone': 'America/Caracas', 'countryCode': 've'},
  {'name': 'Hanoi', 'timezone': 'Asia/Ho_Chi_Minh', 'countryCode': 'vn'},
  {'name': 'Harare', 'timezone': 'Africa/Harare', 'countryCode': 'zw'},
  // Add any other countries or territories you need here
];
